import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";


export const metadata: Metadata = {
  title: "Auction Sphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">   
      <body>
        <Navbar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
